spring.application.name=hrms

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/hrms_visitor
spring.datasource.username=postgres
spring.datasource.password=9696
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate/JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect